# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Faster gradle
org.gradle.daemon=true
org.gradle.vfs.watch=true
org.gradle.caching=true

# Experimental function, can throw errors!
org.gradle.configureondemand=false

# Libraries
paper_api_version=1.21.8-R0.1-SNAPSHOT

# Plugin properties
plugin_version=3.0.1
maven_group=net.sn0wix_
archives_base_name=ModObserverPlugin
mc_compatibility_version=1.21.7+