mode: "whitelist"
allowCommandInterface: true
modObserverRequiredMessage: "This server requires you to install ModObserver. Get it on:\n
  <gold><bold>Curseforge: </bold></gold><gold>curseforge.com/minecraft/mc-mods/mod-observer</gold>\n
  <dark_green><bold>Modrinth: </bold></dark_green><dark_green>modrinth.com/mod/mod-observer</dark_green>"
ignoredPlayers:
