name: ModObserverPlugin
version: '3.0.0'
main: net.sn0wix_.modObserverPlugin.ModObserverPlugin
api-version: '1.21'
authors: [ Sn0wix_ ]
description: Verifies, if the player has installed only permitted mods.
website: https://modrinth.com/plugin/mod-observer-plugin
depend: [ ProtocolLib ]

commands:
  modObserver:
    description: Lets you configure ModObserver plugin.
    usage: /modobserver {value}...
    permission: op